name: 'Release with submodules'
description: 'Add a release asset containig source code with submodules'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ format('./{0}', github.event.repository.name) }}
        submodules: 'recursive'
    - id: create-tar-file
      uses: ./tar-with-submodules
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.create-tar-file.outputs.tar-file-path }}
