name: 'Release with submodules'
description: 'Add a release asset containig source code with submodules'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ format('./{0}', github.event.repository.name) }}
        submodules: 'recursive'
    - run: tar -czvf source_code_with_modules.tar.gz ${{ format('./{0}', github.event.repository.name) }}
      shell: bash
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: source_code_with_modules.tar.gz
